### ISSUE TITLE
Login Button - Unable to log in thru Scatter

### ISSUE THREAD

**Issue by shahidnz** [FreeosDAO/freeos_wallet_frontend#13]
Logged in to Scatter using kylin network and kylin account (api-kylin.eosasia.one; dennisedolan). 
Now launched the portal (https://freeosdao.github.io/) and clicked the Launch button.

There is no error thrown but log in also does not work.

Browser: Safari and Chrome
MacOs Big Saur
```
($ uname -a
Darwin Mohammads-MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64)

```
<img width="1425" alt="Screenshot 2021-01-12 at 8 42 47 PM" src="https://user-images.githubusercontent.com/50853688/104285265-39aac100-5518-11eb-8a34-0067f4bb9484.png">
<img width="1139" alt="Screenshot 2021-01-12 at 8 38 54 PM" src="https://user-images.githubusercontent.com/50853688/104285363-63fc7e80-5518-11eb-90b3-04d723e26702.png">
<img width="1440" alt="Screenshot 2021-01-12 at 8 29 10 PM" src="https://user-images.githubusercontent.com/50853688/104285399-71b20400-5518-11eb-8b1e-fe00eb4512a6.png">

In the console log, getting status 101 - Switching Protocol
```
Request URL: ws://127.0.0.1:50005/socket.io/?EIO=3&transport=websocket
Request Method: GET
Status Code: 101 Switching Protocols
Connection: Upgrade
Sec-WebSocket-Accept: pjvblSHtxt6kfksOe2XEXWk8Q+I=
Upgrade: websocket
```

See the screenshot for more details.

**Comment by ghost** [comment]
Hi Shahid,

I can log in on https://freeosdao.github.io/ in my side. This means that the reason is the difference of Scatter Configuration between you and me. I will send a Scatter Configuration Tutorial written by Tom through Discord.

Thanks for your issues.
Kenneth

**Comment by shahidnz** [comment]
Pls suggest some debug and log options. It works with Tom's see up (Windows). I am using Mac

**Comment by ghost** [comment]
> Pls suggest some debug and log options. It works with Tom's see up (Windows). I am using Mac

Hi Shahid, 

I also use Mac. I suggest you can do a screenshot for Console (not Network) of Chrome development tools

**Comment by shahidnz** [comment]
Hi,

Attaching the console output too. Please refer attachment for more details.
7Unchecked runtime.lastError: The message port closed before a response was received.
app.9cf744ab.js:1 Object
3.b3fd79f8.js:1 Object
3.b3fd79f8.js:1 false
vendor.6dc144b2.js:27 WebSocket connection to 'wss://local.get-scatter.com:50006/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CERT_DATE_INVALID
i @ vendor.6dc144b2.js:27
(anonymous) @ vendor.6dc144b2.js:27
l @ vendor.6dc144b2.js:27
(anonymous) @ vendor.6dc144b2.js:27
(anonymous) @ vendor.6dc144b2.js:27
i @ vendor.6dc144b2.js:34
a @ vendor.6dc144b2.js:34
(anonymous) @ vendor.6dc144b2.js:34
(anonymous) @ vendor.6dc144b2.js:34
(anonymous) @ vendor.6dc144b2.js:27
value @ vendor.6dc144b2.js:27
(anonymous) @ vendor.6dc144b2.js:20
value @ vendor.6dc144b2.js:20
(anonymous) @ vendor.6dc144b2.js:20
(anonymous) @ vendor.6dc144b2.js:20
l @ vendor.6dc144b2.js:27
(anonymous) @ vendor.6dc144b2.js:27
(anonymous) @ vendor.6dc144b2.js:27
i @ vendor.6dc144b2.js:34
a @ vendor.6dc144b2.js:34
(anonymous) @ vendor.6dc144b2.js:34
(anonymous) @ vendor.6dc144b2.js:34
(anonymous) @ vendor.6dc144b2.js:20
e @ vendor.6dc144b2.js:27
g @ vendor.6dc144b2.js:1
q @ app.9cf744ab.js:1
(anonymous) @ vendor.6dc144b2.js:20
_.dispatch @ vendor.6dc144b2.js:20
dispatch @ vendor.6dc144b2.js:20
r.dispatch @ vendor.6dc144b2.js:20
M.forEach.n.<computed> @ vendor.6dc144b2.js:20
click @ 3.b3fd79f8.js:1
ne @ vendor.6dc144b2.js:14
n @ vendor.6dc144b2.js:14
ne @ vendor.6dc144b2.js:14
Tn.t.$emit @ vendor.6dc144b2.js:14
click @ vendor.6dc144b2.js:27
ne @ vendor.6dc144b2.js:14
n @ vendor.6dc144b2.js:14
Jr.o._wrapper @ vendor.6dc144b2.js:14
Show 10 more frames
vendor.6dc144b2.js:27 [scatter] {type: "identity_rejected", message: "User rejected the provision of an Identity", code: 402, isError: true}
vendor.6dc144b2.js:14 {type: "identity_rejected", message: "User rejected the provision of an Identity", code: 402, isError: true}
re @ vendor.6dc144b2.js:14
ie @ vendor.6dc144b2.js:14
ee @ vendor.6dc144b2.js:14
(anonymous) @ vendor.6dc144b2.js:14
Promise.catch (async)
ne @ vendor.6dc144b2.js:14
n @ vendor.6dc144b2.js:14
ne @ vendor.6dc144b2.js:14
Tn.t.$emit @ vendor.6dc144b2.js:14
click @ vendor.6dc144b2.js:27
ne @ vendor.6dc144b2.js:14
n @ vendor.6dc144b2.js:14
Jr.o._wrapper @ vendor.6dc144b2.js:14
<img width="1439" alt="Screenshot 2021-01-18 at 10 20 32 AM" src="https://user-images.githubusercontent.com/50853688/104856347-0bddd600-5977-11eb-8a0f-ab28be5ebf59.png">
<img width="1440" alt="Screenshot 2021-01-18 at 10 20 52 AM" src="https://user-images.githubusercontent.com/50853688/104856351-1009f380-5977-11eb-9946-4ee8e1b70875.png">
