### ISSUE TITLE
Transfer action - entered details are discarded and some internal (or hard coded) values are used.

### ISSUE THREAD

**Issue by shahidnz** [FreeosDAO/freeos_wallet_frontend#21]
Logged in to Scatter with dennisedolan@active account.

Under the Transfer tab, when I opt Send option to execute the Transfer action.
Observed that my entered values such as account name, count does not match and not validated too.

Rather some internally fetched values (or hard coded) are shown.

See the attachments.
<img width="790" alt="Screenshot 2021-01-23 at 10 38 50 AM" src="https://user-images.githubusercontent.com/50853688/105551856-04983d00-5d68-11eb-9a44-2608ea9e54f9.png">
<img width="782" alt="Screenshot 2021-01-23 at 10 42 00 AM" src="https://user-images.githubusercontent.com/50853688/105551869-095cf100-5d68-11eb-95fc-4a45f90d0aa6.png">

**Comment by ai376928387** [comment]
Tranaction page is not finished at that moment
