### ISSUE TITLE
Send Option - no details filled still send does something

### ISSUE THREAD

**Issue by shahidnz** [FreeosDAO/freeos_wallet_frontend#37]
logged in using scatter
jumped to send tab
did not fill any details
clicked send

Web calls are made. 
Expected:
Send should not allow if no valid details are provided

<img width="1278" alt="Screenshot 2021-02-20 at 7 42 54 PM" src="https://user-images.githubusercontent.com/50853688/108586693-f49a6a00-73b4-11eb-98a0-26f0a1e876a9.png">

**Comment by ai376928387** [comment]
fixed
