### ISSUE TITLE
Unable to use Scatter While dropdown gives Scatter option

### ISSUE THREAD

**Issue by shahidnz** [FreeosDAO/freeos_wallet_frontend#39]
launch the portal
Click Login
Choose Scatter

But the pop up of Anchor is displayed. There is no way to log in to it using Scatter
![Screenshot 2021-03-06 122957](https://user-images.githubusercontent.com/50853688/110185738-0a5d6400-7e78-11eb-9a45-7e1ae98646e5.png)
![Screenshot 2021-03-06 123041](https://user-images.githubusercontent.com/50853688/110185742-0c272780-7e78-11eb-83ed-bd8dcd1080f8.png)

**Comment by ai376928387** [comment]
no scatter login will be available. release soon
