### ISSUE TITLE
When the claim page loads, it shows the 'system unavailable' message before displaying the page content

### ISSUE THREAD

**Issue by tommccann777** [FreeosDAO/freeos_wallet_frontend#7]
![2020-12-21 15-30](https://user-images.githubusercontent.com/18106735/102733418-26398980-43a2-11eb-8790-a8332a25dabf.png)

Perhaps this could be solved by assuming a default of masterswitch = '1' as the page loads i.e. assume the system IS available.

**Comment by ghost** [comment]
Resoved.
