### ISSUE TITLE
Frontend loads and automatically logs me in with wrong account

### ISSUE THREAD

**Issue by tommccann777** [FreeosDAO/freeos_wallet_frontend#9]
In Scatter I have account 'alanappleton' selected. On starting the frontend it shows me logged in as 'celiacollins'

![image](https://user-images.githubusercontent.com/18106735/103050841-38156980-45fa-11eb-897e-93c94596f302.png)

![image](https://user-images.githubusercontent.com/18106735/103050919-6dba5280-45fa-11eb-8b34-cfbd8c4d3318.png)

**Comment by ai376928387** [comment]
https://github.com/FreeosDAO/freeos_wallet_frontend/pull/11/files

**Comment by tommccann777** [comment]
Hi Wicky, Happy new year.

How's it going with getting the claim page sorted? Is there anything I
could provide that would help you? Just say and it will be done.

Cheers,

Tom
